
Skip to content
DEV Community
Log in
Create account
Cover image for How to enable GitHub Actions on your Profile README for a snake-eating contribution graph ðŸ
Michelle Mannering
Michelle Mannering

Posted on Jun 28, 2021 â€¢ Updated on Feb 24
How to enable GitHub Actions on your Profile README for a snake-eating contribution graph ðŸ
#github
#markdown
#opensource
#tutorial
Git Good (9 Part Series)
1 Using the GitHub CLI to update your repo
2 How to create and pin a gist on GitHub
... 5 more parts...
8 How to use GitHub Pages to host your website, even with multiple repos
9 How to create a Profile README for your Organisation

Lots of people have been talking about and sharing their GitHub Profile READMEs. It was a project we launched last year and developers are loving it. As this feature became more popular, more developers were building templates, plugins, and apps for you to use on your profile.

This post from Supritha caught my attention. I like the way they talk about various pieces of code to have on your GitHub Profile README.
supritha
How to have an awesome GitHub profile ?
Supritha Ravishankar ãƒ» Jun 8 '21 ãƒ» 5 min read
#github #markdown #opensource #git

One of the comments from Guillaume Falourd pointed to a really cool project from Platane.
GitHub logo Platane / snk
ðŸŸ©â¬œ Generates a snake game from a github user contributions graph and output a screen capture as animated svg or gif
snk

GitHub marketplace type definitions code style

Generates a snake game from a github user contributions graph

Pull a github user's contribution graph Make it a snake Game, generate a snake path where the cells get eaten in an orderly fashion.

Generate a gif or svg image.

Available as github action. Automatically generate a new image at the end of the day. Which makes for great github profile readme
Usage

github action

- uses: Platane/snk@master
  with:
    # github user name to read the contribution graph from (**required**)
    # using action context var `github.repository_owner` or specified user
    github_user_name: ${{ github.repository_owner }}

    # path of the generated gif file
    # If left empty, the gif file will not be generated
    gif_out_path: dist/github-snake.gif

    # path of the generated svg file
    # If left empty, the svg file will not be generated
    svg_out_path: dist/github-snake.svg

    example with cron job

interactive demo

platane.github.io/snk

local

npm install
npm

â€¦
View on GitHub

It uses GitHub Actions to build and update a user's contribution graph, and then has a snake eat all your contributions. The output generates a gif file, that you can then show on your GitHub Profile README. I thought this was pretty cool, so I set about adding this to my profile.
Step 1. Setting up GitHub Actions

The first thing you want to ensure before you start this project, is that you have GitHub Actions setup. Head to your Profile and ensure the "Actions" tab is available. Everyone should now have this feature.

Actions Button

Next, head to Platane's Action (available on the Marketplace) and make a copy of the code. You'll need to add this snippet into your Actions file.
Step 2. Creating your GitHub Actions yaml file

This is definitely the part where I got stuck. When looking at the code, I wasn't sure exactly where to add the lines of code mentioned on Marketplace.

After looking at the way Platane had their Actions file setup, I was able to generate the code (with a little help from Bdougie of course).

I've added the full code snippet below and added plenty of comments to (hopefully make it easy to understand).

You can copy this code straight into a blank *.yml file. Make sure you create a new *.yml file under the following directory:

YOUR_GITHUB_USERNAME --> .github --> workflows --> FILE_NAME.yml


# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.

on:
  schedule:
      # every 6 hours
    - cron: "0 */6 * * *"

# This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2

    # Generates the snake  
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: mishmanners
          # these next 2 lines generate the files on a branch called "output". This keeps the main branch from cluttering up.
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

     # show the status of the build. Makes it easier for debugging (if there's any issues).
      - run: git status

      # Push the changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

Step 3. Running GitHub Actions

Once you've added the code above and committed it, head to your Actions tab. Under "Workflows", you should see the "Generate Snake" Action you created above.

Workflow

Click "Run Workflow" and watch your workflow run. You can even expand your workflow and see what's happening in real time.

Running Actions

Once your workflow has finished running, you should have received a green âœ… "build" checkmark. If so, this means your Action is working nicely. If not, you'll have to go through the code and see where the errors are. The "build" status should give you some indication of where your errors lie. You can also compare it with the yaml file on my GitHub Profile README.

Build green

If you have the green "build" âœ… then you should be good to go. Head back to your repo's "Code" directory, and change your branch to "output". Here you'll find the two versions of your contribution graph with the snake eating it: a *.gif and a *.svg. The good thing about these files is the file is rewritten over itself every time the Action runs. Thus, your contribution graph will always be up to date.

CodeOutput
Step 4. Adding a contribution-eating snake to your profile

Now the final set is to add this to your profile. Grab the file location of your *.gif. It should be something like:

https://github.com/YOUR_USERNAME/YOUR_USERNAME/blob/output/github-contribution-grid-snake.gif

Add this to your profile by copying the file location onto a new line in your markdown file:

![snake gif](https://github.com/YOUR_USERNAME/YOUR_USERNAME/blob/output/github-contribution-grid-snake.gif)

Now you should have a really cool looking snake eating your contributions!

SnakeEating

Hopefully this guide was helpful for you and gives you a good base to start building and adding more Actions on your profile. What have you been adding to your GitHub Profile README? Other there other cool Actions I should be looking at?
Git Good (9 Part Series)
1 Using the GitHub CLI to update your repo
2 How to create and pin a gist on GitHub
... 5 more parts...
8 How to use GitHub Pages to host your website, even with multiple repos
9 How to create a Profile README for your Organisation
Discussion (16)
pic
msoftware profile image
â€¢
Jul 9 '21

Great tutorial! Works for me.
Here's mine - github.com/msoftware
Reply
gustavohgmartins profile image
â€¢
Sep 3 '21

Awsome! How did you change the background-color?
Reply
mishmanners profile image
â€¢
Sep 3 '21

I didn't change the background colour. It's a .png/.svg image, meaning the background is transparent. It looks dark on mine because I have dark mode enabled on GitHub. You can enable it by clicking Settings --> Appearance --> choosing your mode.
Thread
gustavohgmartins profile image
â€¢
Sep 3 '21

Thank you! actually I was using the .gif version, so I switched to the .svg one and voilÃ¡
Thread
mishmanners profile image
â€¢
Sep 3 '21

Awesome! Glad to be of help ðŸ˜„
Reply
bpolaswar profile image
â€¢
Oct 17 '21

Great worked for me. See github.com/bpolaswar
Thanks.
Reply
laurasiiia profile image
â€¢
Jan 2 â€¢ Edited on Jan 2

Hi, i did everything right and even got the "build" status. But no output branch was created... why is that? Can someone help me? github.com/laurasiiia
Reply
mishmanners profile image
â€¢
Jan 4

I assume you're working off this folder: github.com/laurasiiia/laurasiiia/b...

Since you've got a newer repo (mine account was set up a number of years ago), you have the default branch set to "main". You might need to change the code to be "main" instead of "master".

I created a PR for you: github.com/laurasiiia/laurasiiia/p...
(run it and see if that works)... it might not but worth a shot. Feel free to jump in other people ðŸ˜„
Reply
adityamangal1 profile image
â€¢
Jul 22 '21

Awesome Tutorial! ðŸ
Reply
viveeeeeek profile image
â€¢
Oct 2 '21

Awesome!
Reply
zieldecastro profile image
â€¢
Sep 14 '21 â€¢ Edited on Sep 14

It does not work for me. Can someone help me?
github.com/zieldecastro
instagram.com/zieldecastro/
Reply
shasank27 profile image
â€¢
Aug 8 '21 â€¢ Edited on Aug 8

Great tutorial!
But can anyone help me, its not showing all my contributions
github.com/shasank27/shasank27
Reply
mishmanners profile image
â€¢
Sep 6 '21 â€¢ Edited on Sep 6

Hey Shasank. I can't see it on your profile, but to show all contributions, you need to make sure all contributions are turned on your profile. You can do this in your settings:

github.com/YOUR_PROFILE --> Settings --> Profile

Then scroll down to "Contributions" and check the box that says "Include private contributions on my profile".

Hope that helps.
Reply
ichchhagupta profile image
â€¢
Dec 14 '21

Can you please help me in figuring out where to find my actions file mentioned in step 1, so that I can add the required code.
Reply
mishmanners profile image
â€¢
Dec 15 '21

Actions is a feature you'll need to enable for your repo. When you go to your repo, you'll notice a tab called "Actions" that should be next to the "Pull requests" tab. Click the "Actions" tab then you can setup Actions from there.
Reply
adityathakekar profile image
â€¢
Dec 24 '21

works great. thanks a ton.
Reply
Code of Conduct â€¢ Report abuse
Read next
victorneves profile image
Vue.js + Vite - How to dynamically inline SVG's without 3rd party libraries

Victor Neves - Mar 13
duncanlew profile image
Getting started with Markdown in Google Docs

Duncan Lew - Apr 2
madza profile image
19 Valuable GitHub Repositories for Beginner Developers ðŸ“šâœ¨

Madza - Mar 1
mlhekinci profile image
How to Multipart File Upload Using FormData with React Hook Form

Melih Ekinci - Mar 31
Michelle Mannering
Developer Advocate | Hackathon Queen | International Speaker

    Location
    Australia
    Education
    The University of Melbourne
    Work
    Developer Advocate at GitHub
    Joined
    May 29, 2020

More from Michelle Mannering
How to create a healthy and sustainable open source community
#github #opensource #tutorial
Shipping a new open source project? Have you thought about release naming?
#tutorial #discuss #release #programming
Customise GitHub Mobile to work better for you: Shortcuts and more
#productivity #tutorial #github #mobile


# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.

on:
  schedule:
      # every 6 hours
    - cron: "0 */6 * * *"

# This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2

    # Generates the snake  
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: mishmanners
          # these next 2 lines generate the files on a branch called "output". This keeps the main branch from cluttering up.
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

     # show the status of the build. Makes it easier for debugging (if there's any issues).
      - run: git status

      # Push the changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

DEV Community â€” A constructive and inclusive social network for software developers. With you every step of your journey.

Built on Forem â€” the open source software that powers DEV and other inclusive communities.

Made with love and Ruby on Rails. DEV Community Â© 2016 - 2022.
